# basic options
title: Byron H
email: byhay1[at]terpmail.umd.edu
description:  
github_username: byhay1 
linkedin_username: byron-h-a1a7a122
url: https://byhay1.github.io/

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
text-transform: False
math: True
